# Generated by Django 5.1.4 on 2024-12-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_user',
            new_name='is_customer',
        ),
    ]
