# Generated by Django 5.0.6 on 2024-12-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_book_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sulg',
            new_name='slug',
        ),
    ]
