# Generated by Django 5.0.6 on 2024-12-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
